services:
  cs2-server:
    image: joedwards32/cs2:latest
    container_name: cs2-server
    user: root
    environment:
      # Server configuration
      - SRCDS_TOKEN=69D0D42E5D47B56203CA5E287FC8C662                 # Game Server Token from https://steamcommunity.com/dev/managegameservers
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
      - DEBUG=0                     # (0 - off, 1 - steamcmd, 2 - cs2, 3 - all)
      - STEAMAPPVALIDATE=0          # (0 - no validation, 1 - enable validation)
      - CS2_SERVERNAME=changeme     # (Set the visible name for your private server.)
      - CS2_CHEATS=1                # (0 - disable cheats, 1 - enable cheats)
      - CS2_PORT=27015              # (CS2 server listen port tcp_udp)
      - CS2_SERVER_HIBERNATE=0      # (Put server in a low CPU state when there are no players. 0 - hibernation disabled, 1 - hibernation enabled)
      - CS2_RCON_PORT               # (Optional, use a simple TCP proxy to have RCON listen on an alternative port. Useful for services like AWS Fargate which do not support mixed protocol ports.)
      - CS2_LAN=0                   # (0 - LAN mode disabled, 1 - LAN Mode enabled)
      - CS2_RCONPW=changeme         # (RCON password)
      - CS2_PW                      # (Optional, CS2 server password)
      - CS2_MAXPLAYERS=14           # (Max players)
      - CS2_ADDITIONAL_ARGS         # (Optional additional arguments to pass into cs2)
      - CS2_CFG_URL                 # HTTP/HTTPS URL to fetch a Tar Gzip bundle, Tar or Zip archive of configuration files/mods
      # Game modes
      - CS2_GAMEALIAS               # (Game type, e.g. casual, competitive, deathmatch. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMETYPE=0              # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMEMODE=1              # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_MAPGROUP=mg_active      # (Map pool. Ignored if Workshop maps are defined.)
      - CS2_STARTMAP=de_mirage     # (Start map. Ignored if Workshop maps are defined.)
      # Workshop Maps
      - CS2_HOST_WORKSHOP_COLLECTION # The workshop collection to use
      - CS2_HOST_WORKSHOP_MAP        # The workshop map to use. If collection is also defined, this is the starting map.
      # Bots
      - CS2_BOT_DIFFICULTY=3          # (0 - easy, 1 - normal, 2 - hard, 3 - expert)
      - CS2_BOT_QUOTA=12           # (Number of bots)
      - CS2_BOT_QUOTA_MODE=fill          # (fill, competitive)
      # TV
      - TV_AUTORECORD=0             # Automatically records all games as CSTV demos: 0=off, 1=on.
      - TV_ENABLE=0                 # Activates CSTV on server: 0=off, 1=on.
      - TV_PORT=27020               # Host SourceTV port
      - TV_PW=changeme              # CSTV password for clients
      - TV_RELAY_PW=changeme        # CSTV password for relay proxies
      - TV_MAXRATE=0                # World snapshots to broadcast per second. Affects camera tickrate.
      - TV_DELAY=0                  # CSTV broadcast delay in seconds
      # Logs
      - CS2_LOG=on                  # 'on'/'off'
      - CS2_LOG_MONEY=0             # Turns money logging on/off: (0=off, 1=on)
      - CS2_LOG_DETAIL=0            # Combat damage logging: (0=disabled, 1=enemy, 2=friendly, 3=all)
      - CS2_LOG_ITEMS=0             # Turns item logging on/off: (0=off, 1=on)
    volumes:
      # ðŸ”’ Container-eigenes Volume (keine Permission-Probleme)
      - cs2-data:/home/steam/cs2-dedicated/

      # Pre-hook
      - ./entry.sh:/home/steam/entry.sh
      - ./pre.sh:/pre.sh
      - ./cs2-seed:/seed:ro
    entrypoint: ["/bin/bash", "/home/steam/entry.sh"]
    networks:
      - cs2-network
    ports:
      - "27015:27015/tcp"           # TCP
      - "27015:27015/udp"           # UDP
      - "27020:27020/udp"           # UDP

  cs2-db:
    image: mariadb:latest
    container_name: cs2-db2
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=cs2
      - MARIADB_USER=cs2
      - MARIADB_PASSWORD=cs2password
    volumes:
      - ./cs2-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - cs2-network

networks:
  cs2-network:
    driver: bridge

volumes:
  cs2-data:
  cs2-db-data:
